chore(gmdmf-10): updated workflow to create cloud front

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -28,20 +28,49 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Get S3 website URL and output
-        id: get_s3_url
-        env: 
-          BUCKET_NAME: ${{ inputs.project_name }}-${{ inputs.environment }}-v3
-          VERSION: ${{ inputs.new_version }}
-          REGION: ${{ secrets.AWS_REGION }}
+      - name: Install AWS CLI
         run: |
-          # BUCKET_NAME="${{ inputs.project_name }}-${{ inputs.environment }}-v3"
-          # VERSION=${{ inputs.new_version }}
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip awscliv2.zip
+          sudo ./aws/install --update
 
-          # Construct website URL
-          WEBSITE_URL="http://$BUCKET_NAME.s3-website.$REGION.amazonaws.com/$VERSION/"
+      - name: Configure AWS credentials using OIDC
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: ${{ secrets.AWS_ROLE }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          mask-aws-account-id: no
+
+      - name: Get CloudFront URL and output
+        id: get_cf_url
+        env:
+          PROJECT_NAME: ${{ inputs.project_name }}
+          ENVIRONMENT: ${{ inputs.environment }}
+          VERSION: ${{ inputs.new_version }}
+        run: |
+          CF_DOMAIN_NAME=$(aws cloudfront list-distributions --query "DistributionList.Items[?Origins.Items[?DomainName=='${PROJECT_NAME}-${ENVIRONMENT}-v3.s3-website.${{ secrets.AWS_REGION }}.amazonaws.com']].DomainName" --output text)
+          if [ -z "$CF_DOMAIN_NAME" ]; then
+            echo "Error: CloudFront distribution not found."
+            exit 1
+          fi
+          WEBSITE_URL="https://$CF_DOMAIN_NAME/$VERSION/"
 
           echo "link=$WEBSITE_URL" >> $GITHUB_ENV
+
+      # - name: Get S3 website URL and output
+      #   id: get_s3_url
+      #   env:
+      #     BUCKET_NAME: ${{ inputs.project_name }}-${{ inputs.environment }}-v3
+      #     VERSION: ${{ inputs.new_version }}
+      #     REGION: ${{ secrets.AWS_REGION }}
+      #   run: |
+      #     # BUCKET_NAME="${{ inputs.project_name }}-${{ inputs.environment }}-v3"
+      #     # VERSION=${{ inputs.new_version }}
+
+      #     # Construct website URL
+      #     WEBSITE_URL="http://$BUCKET_NAME.s3-website.$REGION.amazonaws.com/$VERSION/"
+
+      #     echo "link=$WEBSITE_URL" >> $GITHUB_ENV
 
       - name: Generate release notes
         id: generate_release_notes
